@startuml
left to right direction
skinparam packageStyle rectangle
actor "slutbruker" as s
actor "admin" as ad
rectangle prototype{
    usecase "login" as UC1
    usecase "registrering" as UC2
    usecase "söke felt" as UC3
    usecase "betalings lösnig" as UC4
    usecase "velge levering" as UC5
    usecase "info om varen" as UC6
    usecase "sende inn bilde" as UC7
    usecase "legge til favorit" as UC8
    usecase "heve kjöp" as UC9
    usecase "klage og returnere" as UC10
    usecase "se senest sett varer" as UC11
    usecase "slette bruker" as UC12
}

s --> UC1
UC1 <-- ad
s --> UC2
UC2 <-- ad
s --> UC3
s --> UC4

s --> UC5
s --> UC6
UC6 <-- ad
s --> UC7
UC7 <-- ad
s --> UC8
s --> UC9
s --> UC10
s --> UC11
s --> UC12
UC12 <-- ad


@enduml
